# Generated by Django 4.1.5 on 2023-01-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=1000)),
                ('image_link', models.CharField(max_length=1000)),
                ('item_price', models.CharField(max_length=1000)),
                ('item_desc', models.CharField(max_length=1000)),
            ],
        ),
    ]
